version: "3.0"

networks: 
  jenkins-network:
    
volumes:
  jenkins-home-volume:
  
services:
  jenkins:
    user: root
    container_name: jenkins-master
    ports:
      - 8081:8080
      - 50001:50000
    networks:
      - jenkins-network
    volumes:
      - jenkins-home-volume:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    image: jenkins/jenkins:lts