version: "3.7"

networks:
  jenkins-network:

volumes:
  jenkins-home-volume:

services:
  jenkins-service:
    image: jenkins/jenkins:lts
    user: root
    privileged: true
    container_name: jenkins-master
    ports:
      - 8081:8080
      - 50001:50000
    networks:
      - jenkins-network
    volumes:
      - jenkins-home-volume:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins-agent-service:
    image: jenkins/ssh-agent:latest-jdk11
    user: root
    privileged: true
    container_name: jenkins-agent
    ports:
      - 22:22
    expose:
      - "22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDn89K7/mlWB6jODUQupW7eTPCCj5JE+lroDTnrP2J5qk8ok4nYjU4DsQdBMQLfHC1jk/2yS9xkoXWuFl+gYfVErC0KNGrt+puOQSOyPoQPLF9yFuThh5Wd4+gJIBGTl+3MT6zTdafHyrVsYfxrKlXBlO4ZOdgWS20eMmBYLuaZTsZn9OSepniD0EeAPhmtl6FQTJPFOgJTkwVP75uAWDmvcc+jYZMpc4X4MLstX210VsbsEu+ajJvdiHHR2m/vp0vrmytMyGtX2lctNTZG42u62vSSFEgIPRRKL0DBjDnhtJQT6daC4F5QoBwgdl7CdwTbzKi8WYXeVk2KY35OcO3icKrwbVz+A8m33oxgHBc/feQLNSs4jSPIaNOen+jBeIXVxd/v861xgwdyOcd9mM/CBjuXDW9mgufZb4CQyW9bvBVHzrPssm4L1h9nnxA91YMGp4BsiwGRaAvZBLfUKZY7ePPag30Cbe81/J6Miijw8F9R+aIMD5Hu2eqSrfAzBz0= ash\ash@ash